# Generated by Django 4.2.2 on 2023-06-23 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_equip', models.CharField(max_length=100)),
                ('ciutat', models.CharField(max_length=100)),
                ('estadi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Partit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gols_locals', models.IntegerField()),
                ('gols_visitants', models.IntegerField()),
                ('data_partit', models.DateField()),
                ('equip_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equip_local', to='lliga.equip')),
                ('equip_visitant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equip_visitant', to='lliga.equip')),
            ],
        ),
        migrations.CreateModel(
            name='Lliga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_temporada', models.CharField(max_length=100)),
                ('equips', models.ManyToManyField(to='lliga.equip')),
            ],
            options={
                'verbose_name_plural': 'Lligues',
            },
        ),
        migrations.CreateModel(
            name='Jugadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('cognom', models.CharField(max_length=100)),
                ('dorsal', models.IntegerField()),
                ('equip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lliga.equip')),
            ],
            options={
                'verbose_name_plural': 'Jugadores',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipus_event', models.CharField(max_length=100)),
                ('temps', models.TimeField()),
                ('jugadora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_fets', to='lliga.jugadora')),
                ('partit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lliga.partit')),
            ],
        ),
    ]
