# Generated by Django 4.2.2 on 2023-06-23 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lliga', '0002_alter_lliga_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='partit',
            name='lliga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lliga.lliga'),
        ),
    ]
