# Generated by Django 4.2.2 on 2023-07-01 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lliga', '0003_partit_lliga'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equip',
            old_name='nom_equip',
            new_name='nom',
        ),
        migrations.RemoveField(
            model_name='event',
            name='jugadora',
        ),
        migrations.RemoveField(
            model_name='event',
            name='tipus_event',
        ),
        migrations.AddField(
            model_name='event',
            name='equip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lliga.equip'),
        ),
        migrations.AddField(
            model_name='event',
            name='tipus',
            field=models.CharField(choices=[('GOL', 'Gol'), ('AUTOGOL', 'Autogol'), ('FALTA', 'Falta'), ('PENALTY', 'Penalty'), ('MANS', 'Mans'), ('CESSIO', 'Cessio'), ('FORA_DE_JOC', 'Fora De Joc'), ('ASSISTENCIA', 'Assistencia'), ('TARGETA_GROGA', 'Targeta Groga'), ('TARGETA_VERMELLA', 'Targeta Vermella')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='partit',
            name='detalls',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partit',
            name='inici',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partit',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partits_local', to='lliga.equip'),
        ),
        migrations.AddField(
            model_name='partit',
            name='visitant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partits_visitant', to='lliga.equip'),
        ),
        migrations.AlterField(
            model_name='event',
            name='temps',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='partit',
            name='lliga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lliga.lliga'),
        ),
        migrations.AlterUniqueTogether(
            name='partit',
            unique_together={('local', 'visitant', 'lliga')},
        ),
        migrations.RemoveField(
            model_name='partit',
            name='data_partit',
        ),
        migrations.RemoveField(
            model_name='partit',
            name='equip_local',
        ),
        migrations.RemoveField(
            model_name='partit',
            name='equip_visitant',
        ),
        migrations.RemoveField(
            model_name='partit',
            name='gols_locals',
        ),
        migrations.RemoveField(
            model_name='partit',
            name='gols_visitants',
        ),
    ]
