# Generated by Django 4.2.2 on 2023-07-01 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lliga', '0004_rename_nom_equip_equip_nom_remove_event_jugadora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='detalls',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='jugador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_fets', to='lliga.jugadora'),
        ),
        migrations.AddField(
            model_name='event',
            name='jugador2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_rebuts', to='lliga.jugadora'),
        ),
        migrations.AlterField(
            model_name='event',
            name='temps',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='tipus',
            field=models.CharField(choices=[('GOL', 'Gol'), ('AUTOGOL', 'Autogol'), ('FALTA', 'Falta'), ('PENALTY', 'Penalty'), ('MANS', 'Mans'), ('CESSIO', 'Cessio'), ('FORA_DE_JOC', 'Fora De Joc'), ('ASSISTENCIA', 'Assistencia'), ('TARGETA_GROGA', 'Targeta Groga'), ('TARGETA_VERMELLA', 'Targeta Vermella')], max_length=30),
        ),
    ]
