# Generated by Django 4.2.2 on 2023-07-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lliga', '0005_event_detalls_event_jugador_event_jugador2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equip',
            options={'verbose_name_plural': 'Lligues'},
        ),
        migrations.AlterField(
            model_name='equip',
            name='ciutat',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equip',
            name='estadi',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
