# Generated by Django 4.2.2 on 2023-07-04 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lliga', '0006_alter_equip_options_alter_equip_ciutat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equip',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lliga',
            options={'verbose_name_plural': 'Lligues'},
        ),
    ]
